feat(locales): add typesafe
MenheraBot/MenheraBot pull request #172
Opened 2021-11-02 22:31 UTC by Tsugami

**What did you change in this PR?**
adds typing in locales to avoid typos

**Why should this change be made?**
safety.

**Why should we accept this change?**
Closes #143

2021-11-02 22:38 UTC, almeidx requested changes

2021-11-02 22:38 UTC, almeidx commented on src/types/i18next.d.ts
> +export type Translation = TokenTranslation<Resources>;
```suggestion
export type Translation<R extends boolean = false> = Extract<
  keyof {
    [Key in Extract<keyof Resources, string> as Resources[Key] extends string | number
      ? `${Key}`
      : `${Key}${R extends true ? '.' : ':'}${Translation<Resources[Key], true>}`]: unknown;
  },
  string
>;
```

2021-11-03 00:52 UTC, ySnoopyDogy approved these changes
Pelo q to vendo ta safe, só me fala oq fazer com a sujestao do almeida ali pq esses types me bugam tudo n entendo nada

2021-11-03 21:10 UTC, Tsugami commented on src/types/i18next.d.ts
> +export type Translation = TokenTranslation<Resources>;
is separate for other future tokens

2021-11-03 21:11 UTC, merged